theme: jekyll-theme-cayman
title: Protocolos estandarizados de operación (SOP) | Genómica Ambiental FC-UNAM
description: En este sitio vamos a sistematizar los protocolos estandarizados de operacion del laboratorio en nuestro análisis rutinarios de amplicones, metagenomas y genomas
show_downloads: "true"


